# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0015_contact_suppress_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bill_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='bill_terms',
            field=models.CharField(blank=True, choices=[('DAYSAFTERBILLDATE', 'day(s) after bill date'), ('DAYSAFTERBILLMONTH', 'day(s) after bill month'), ('OFCURRENTMONTH', 'of the current month'), ('OFFOLLOWINGMONTH', 'of the following month')], max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='invoice_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='invoice_terms',
            field=models.CharField(blank=True, choices=[('DAYSAFTERBILLDATE', 'day(s) after bill date'), ('DAYSAFTERBILLMONTH', 'day(s) after bill month'), ('OFCURRENTMONTH', 'of the current month'), ('OFFOLLOWINGMONTH', 'of the following month')], max_length=20),
        ),
    ]
