# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0016_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
