# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0017_contact_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='suppress_due_date',
        ),
    ]
