# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-14 12:11
from __future__ import unicode_literals

from django.db import migrations
import invoicer.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0018_remove_contact_suppress_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=invoicer.models.CICharField(max_length=30, unique=True),
        ),
    ]
