# Generated by Django 3.1.13 on 2021-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0020_auto_20210416_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='isBill',
            field=models.BooleanField(help_text="Match on whether we are preparing an invoice or a bill; 'Unknown' matches either way", null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='isSwap',
            field=models.BooleanField(help_text="Match on whether the product has the 'swap' tickbox set; 'Unknown' matches either way", null=True),
        ),
    ]
